// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/nabu.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Project struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Repository           string   `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{0}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Project) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Project) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

type Repository struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string    `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Branches             []*Branch `protobuf:"bytes,4,rep,name=branches,proto3" json:"branches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{1}
}
func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (dst *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(dst, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Repository) GetBranches() []*Branch {
	if m != nil {
		return m.Branches
	}
	return nil
}

type Branch struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Commits              []*Commit `protobuf:"bytes,3,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Branch) Reset()         { *m = Branch{} }
func (m *Branch) String() string { return proto.CompactTextString(m) }
func (*Branch) ProtoMessage()    {}
func (*Branch) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{2}
}
func (m *Branch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Branch.Unmarshal(m, b)
}
func (m *Branch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Branch.Marshal(b, m, deterministic)
}
func (dst *Branch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Branch.Merge(dst, src)
}
func (m *Branch) XXX_Size() int {
	return xxx_messageInfo_Branch.Size(m)
}
func (m *Branch) XXX_DiscardUnknown() {
	xxx_messageInfo_Branch.DiscardUnknown(m)
}

var xxx_messageInfo_Branch proto.InternalMessageInfo

func (m *Branch) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Branch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Branch) GetCommits() []*Commit {
	if m != nil {
		return m.Commits
	}
	return nil
}

type Commit struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sha                  string   `protobuf:"bytes,3,opt,name=sha,proto3" json:"sha,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{3}
}
func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (dst *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(dst, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Commit) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Commit) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *Commit) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ListProjectsResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{4}
}
func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (dst *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(dst, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ListCommitsResponse struct {
	Commit               *Commit  `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCommitsResponse) Reset()         { *m = ListCommitsResponse{} }
func (m *ListCommitsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommitsResponse) ProtoMessage()    {}
func (*ListCommitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{5}
}
func (m *ListCommitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommitsResponse.Unmarshal(m, b)
}
func (m *ListCommitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommitsResponse.Marshal(b, m, deterministic)
}
func (dst *ListCommitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommitsResponse.Merge(dst, src)
}
func (m *ListCommitsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommitsResponse.Size(m)
}
func (m *ListCommitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommitsResponse proto.InternalMessageInfo

func (m *ListCommitsResponse) GetCommit() *Commit {
	if m != nil {
		return m.Commit
	}
	return nil
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{6}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type ProjectRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectRequest) Reset()         { *m = ProjectRequest{} }
func (m *ProjectRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectRequest) ProtoMessage()    {}
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{7}
}
func (m *ProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRequest.Unmarshal(m, b)
}
func (m *ProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRequest.Marshal(b, m, deterministic)
}
func (dst *ProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRequest.Merge(dst, src)
}
func (m *ProjectRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectRequest.Size(m)
}
func (m *ProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRequest proto.InternalMessageInfo

func (m *ProjectRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateProjectRequest struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repository           *Repository `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_c55c12469c4ded39, []int{8}
}
func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (dst *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(dst, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func init() {
	proto.RegisterType((*Project)(nil), "protobuf.Project")
	proto.RegisterType((*Repository)(nil), "protobuf.Repository")
	proto.RegisterType((*Branch)(nil), "protobuf.Branch")
	proto.RegisterType((*Commit)(nil), "protobuf.Commit")
	proto.RegisterType((*ListProjectsResponse)(nil), "protobuf.ListProjectsResponse")
	proto.RegisterType((*ListCommitsResponse)(nil), "protobuf.ListCommitsResponse")
	proto.RegisterType((*EmptyRequest)(nil), "protobuf.EmptyRequest")
	proto.RegisterType((*ProjectRequest)(nil), "protobuf.ProjectRequest")
	proto.RegisterType((*CreateProjectRequest)(nil), "protobuf.CreateProjectRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NabuServiceClient is the client API for NabuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NabuServiceClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	ListProjects(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (NabuService_ListProjectsClient, error)
	ListCommits(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (NabuService_ListCommitsClient, error)
}

type nabuServiceClient struct {
	cc *grpc.ClientConn
}

func NewNabuServiceClient(cc *grpc.ClientConn) NabuServiceClient {
	return &nabuServiceClient{cc}
}

func (c *nabuServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.NabuService/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nabuServiceClient) ListProjects(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (NabuService_ListProjectsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NabuService_serviceDesc.Streams[0], "/protobuf.NabuService/ListProjects", opts...)
	if err != nil {
		return nil, err
	}
	x := &nabuServiceListProjectsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NabuService_ListProjectsClient interface {
	Recv() (*ListProjectsResponse, error)
	grpc.ClientStream
}

type nabuServiceListProjectsClient struct {
	grpc.ClientStream
}

func (x *nabuServiceListProjectsClient) Recv() (*ListProjectsResponse, error) {
	m := new(ListProjectsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nabuServiceClient) ListCommits(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (NabuService_ListCommitsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NabuService_serviceDesc.Streams[1], "/protobuf.NabuService/ListCommits", opts...)
	if err != nil {
		return nil, err
	}
	x := &nabuServiceListCommitsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NabuService_ListCommitsClient interface {
	Recv() (*ListCommitsResponse, error)
	grpc.ClientStream
}

type nabuServiceListCommitsClient struct {
	grpc.ClientStream
}

func (x *nabuServiceListCommitsClient) Recv() (*ListCommitsResponse, error) {
	m := new(ListCommitsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NabuServiceServer is the server API for NabuService service.
type NabuServiceServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*ListProjectsResponse, error)
	ListProjects(*EmptyRequest, NabuService_ListProjectsServer) error
	ListCommits(*ProjectRequest, NabuService_ListCommitsServer) error
}

func RegisterNabuServiceServer(s *grpc.Server, srv NabuServiceServer) {
	s.RegisterService(&_NabuService_serviceDesc, srv)
}

func _NabuService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NabuServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.NabuService/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NabuServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NabuService_ListProjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NabuServiceServer).ListProjects(m, &nabuServiceListProjectsServer{stream})
}

type NabuService_ListProjectsServer interface {
	Send(*ListProjectsResponse) error
	grpc.ServerStream
}

type nabuServiceListProjectsServer struct {
	grpc.ServerStream
}

func (x *nabuServiceListProjectsServer) Send(m *ListProjectsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NabuService_ListCommits_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NabuServiceServer).ListCommits(m, &nabuServiceListCommitsServer{stream})
}

type NabuService_ListCommitsServer interface {
	Send(*ListCommitsResponse) error
	grpc.ServerStream
}

type nabuServiceListCommitsServer struct {
	grpc.ServerStream
}

func (x *nabuServiceListCommitsServer) Send(m *ListCommitsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _NabuService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.NabuService",
	HandlerType: (*NabuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _NabuService_CreateProject_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProjects",
			Handler:       _NabuService_ListProjects_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListCommits",
			Handler:       _NabuService_ListCommits_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/nabu.proto",
}

func init() { proto.RegisterFile("protobuf/nabu.proto", fileDescriptor_nabu_c55c12469c4ded39) }

var fileDescriptor_nabu_c55c12469c4ded39 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0xab, 0xd3, 0x30,
	0x14, 0xc7, 0x69, 0x3b, 0xdb, 0x7b, 0x4f, 0xaf, 0x63, 0x66, 0x45, 0x82, 0xe8, 0x28, 0x79, 0x2a,
	0x2a, 0x73, 0x4c, 0xdf, 0x05, 0x87, 0xb0, 0x07, 0x71, 0x12, 0x5f, 0x7c, 0x34, 0xed, 0xa2, 0x8b,
	0xda, 0x1f, 0x36, 0xa9, 0xb0, 0x7f, 0xdb, 0xbf, 0x40, 0x96, 0x36, 0x6b, 0xd6, 0x0e, 0xbc, 0x6f,
	0x39, 0xdf, 0x73, 0xf8, 0x9c, 0x73, 0xbe, 0x39, 0x30, 0xaf, 0xea, 0x52, 0x95, 0x69, 0xf3, 0xed,
	0x55, 0xc1, 0xd2, 0x66, 0xa9, 0x23, 0x74, 0x63, 0x44, 0xb2, 0x83, 0xe0, 0x53, 0x5d, 0xfe, 0xe0,
	0x99, 0x42, 0x53, 0x70, 0xc5, 0x1e, 0x3b, 0xb1, 0x93, 0x78, 0xd4, 0x15, 0x7b, 0x14, 0xc1, 0x03,
	0x25, 0xd4, 0x2f, 0x8e, 0xdd, 0xd8, 0x49, 0x6e, 0x69, 0x1b, 0xa0, 0x05, 0x40, 0xcd, 0xab, 0x52,
	0x0a, 0x55, 0xd6, 0x47, 0xec, 0xe9, 0x94, 0xa5, 0x90, 0x0a, 0x80, 0x9e, 0xa3, 0x11, 0x13, 0xc1,
	0xa4, 0x60, 0xb9, 0x41, 0xea, 0x37, 0x9a, 0x81, 0xf7, 0x93, 0x1b, 0xd4, 0xe9, 0x89, 0x5e, 0xc2,
	0x4d, 0x5a, 0xb3, 0x22, 0x3b, 0x70, 0x89, 0x27, 0xb1, 0x97, 0x84, 0xeb, 0xd9, 0xd2, 0x4c, 0xbc,
	0x7c, 0xa7, 0x33, 0xf4, 0x5c, 0x41, 0xbe, 0x80, 0xdf, 0x6a, 0xf7, 0xea, 0xf6, 0x1c, 0x82, 0xac,
	0xcc, 0x73, 0xa1, 0x24, 0xf6, 0x86, 0xe8, 0x8d, 0x4e, 0x50, 0x53, 0x40, 0x52, 0xf0, 0x5b, 0x69,
	0x44, 0xc6, 0x10, 0xe4, 0x5c, 0x4a, 0xf6, 0xdd, 0xc0, 0x4d, 0x78, 0xda, 0x46, 0x1e, 0x98, 0xd9,
	0x46, 0x1e, 0x18, 0x7a, 0x0a, 0xb7, 0x4a, 0xe4, 0x5c, 0x2a, 0x96, 0x57, 0x78, 0xa2, 0x11, 0xbd,
	0x40, 0x36, 0x10, 0x7d, 0x10, 0x52, 0x75, 0x9f, 0x20, 0x29, 0x97, 0x55, 0x59, 0x48, 0x8e, 0x5e,
	0x40, 0x50, 0xb5, 0x9a, 0x6e, 0x1b, 0xae, 0x1f, 0xf5, 0x73, 0x76, 0xc5, 0xd4, 0x54, 0x90, 0xb7,
	0x30, 0x3f, 0x41, 0xda, 0x61, 0x7b, 0x46, 0x02, 0x7e, 0xbb, 0x4a, 0x87, 0x18, 0xaf, 0xda, 0xe5,
	0xc9, 0x14, 0xee, 0xde, 0xe7, 0x95, 0x3a, 0x52, 0xfe, 0xbb, 0xe1, 0x52, 0x91, 0x18, 0xa6, 0xa6,
	0x49, 0xab, 0x0c, 0x1d, 0x20, 0x5f, 0x21, 0xda, 0xd4, 0x9c, 0x29, 0x3e, 0xa8, 0x33, 0x9e, 0x3b,
	0x96, 0xe7, 0x6f, 0x2e, 0x6e, 0xc6, 0xd5, 0xb3, 0x44, 0xfd, 0x2c, 0xfd, 0xbd, 0xd8, 0x97, 0xb4,
	0xfe, 0xeb, 0x40, 0xf8, 0x91, 0xa5, 0xcd, 0x67, 0x5e, 0xff, 0x11, 0x19, 0x47, 0x3b, 0x78, 0x78,
	0xd1, 0x11, 0x2d, 0xac, 0x75, 0xae, 0x8c, 0xf2, 0xc4, 0xca, 0x5f, 0xb5, 0x78, 0x0b, 0x77, 0xb6,
	0x8e, 0x1e, 0xf7, 0xf5, 0xb6, 0x19, 0xff, 0xe3, 0xac, 0x1c, 0xb4, 0x85, 0xd0, 0xf2, 0x1f, 0xe1,
	0xf1, 0x57, 0x75, 0xa8, 0x67, 0x97, 0xa8, 0xc1, 0x87, 0xad, 0x9c, 0xd4, 0xd7, 0xf9, 0xd7, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x32, 0x36, 0x19, 0xb7, 0x03, 0x00, 0x00,
}
