// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/nabu.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusType int32

const (
	StatusType_UNKNOWN StatusType = 0
	StatusType_SUCCESS StatusType = 1
	StatusType_ERROR   StatusType = 2
	StatusType_WARNING StatusType = 3
	StatusType_PENDING StatusType = 4
)

var StatusType_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "ERROR",
	3: "WARNING",
	4: "PENDING",
}
var StatusType_value = map[string]int32{
	"UNKNOWN": 0,
	"SUCCESS": 1,
	"ERROR":   2,
	"WARNING": 3,
	"PENDING": 4,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{0}
}

type Project struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Repository           string   `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{0}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Project) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Project) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

type Repository struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string    `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Branches             []*Branch `protobuf:"bytes,4,rep,name=branches,proto3" json:"branches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{1}
}
func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (dst *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(dst, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Repository) GetBranches() []*Branch {
	if m != nil {
		return m.Branches
	}
	return nil
}

type Branch struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Commits              []*Commit `protobuf:"bytes,3,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Branch) Reset()         { *m = Branch{} }
func (m *Branch) String() string { return proto.CompactTextString(m) }
func (*Branch) ProtoMessage()    {}
func (*Branch) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{2}
}
func (m *Branch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Branch.Unmarshal(m, b)
}
func (m *Branch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Branch.Marshal(b, m, deterministic)
}
func (dst *Branch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Branch.Merge(dst, src)
}
func (m *Branch) XXX_Size() int {
	return xxx_messageInfo_Branch.Size(m)
}
func (m *Branch) XXX_DiscardUnknown() {
	xxx_messageInfo_Branch.DiscardUnknown(m)
}

var xxx_messageInfo_Branch proto.InternalMessageInfo

func (m *Branch) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Branch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Branch) GetCommits() []*Commit {
	if m != nil {
		return m.Commits
	}
	return nil
}

type Commit struct {
	Message              string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sha                  string               `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{3}
}
func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (dst *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(dst, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Commit) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *Commit) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Message struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status               StatusType           `protobuf:"varint,4,opt,name=status,proto3,enum=protobuf.StatusType" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{4}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Message) GetStatus() StatusType {
	if m != nil {
		return m.Status
	}
	return StatusType_UNKNOWN
}

type BuildRequest struct {
	ProjectId            int64    `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{5}
}
func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (dst *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(dst, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetProjectId() int64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *BuildRequest) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type BuildResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{6}
}
func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (dst *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(dst, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type ListProjectsResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{7}
}
func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (dst *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(dst, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ListBranchesResponse struct {
	Branch               *Branch  `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBranchesResponse) Reset()         { *m = ListBranchesResponse{} }
func (m *ListBranchesResponse) String() string { return proto.CompactTextString(m) }
func (*ListBranchesResponse) ProtoMessage()    {}
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{8}
}
func (m *ListBranchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBranchesResponse.Unmarshal(m, b)
}
func (m *ListBranchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBranchesResponse.Marshal(b, m, deterministic)
}
func (dst *ListBranchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBranchesResponse.Merge(dst, src)
}
func (m *ListBranchesResponse) XXX_Size() int {
	return xxx_messageInfo_ListBranchesResponse.Size(m)
}
func (m *ListBranchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBranchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBranchesResponse proto.InternalMessageInfo

func (m *ListBranchesResponse) GetBranch() *Branch {
	if m != nil {
		return m.Branch
	}
	return nil
}

type ListCommitsResponse struct {
	Commit               *Commit  `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCommitsResponse) Reset()         { *m = ListCommitsResponse{} }
func (m *ListCommitsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommitsResponse) ProtoMessage()    {}
func (*ListCommitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{9}
}
func (m *ListCommitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommitsResponse.Unmarshal(m, b)
}
func (m *ListCommitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommitsResponse.Marshal(b, m, deterministic)
}
func (dst *ListCommitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommitsResponse.Merge(dst, src)
}
func (m *ListCommitsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommitsResponse.Size(m)
}
func (m *ListCommitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommitsResponse proto.InternalMessageInfo

func (m *ListCommitsResponse) GetCommit() *Commit {
	if m != nil {
		return m.Commit
	}
	return nil
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{10}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type BranchRequest struct {
	RepoId               int64    `protobuf:"varint,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BranchRequest) Reset()         { *m = BranchRequest{} }
func (m *BranchRequest) String() string { return proto.CompactTextString(m) }
func (*BranchRequest) ProtoMessage()    {}
func (*BranchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{11}
}
func (m *BranchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchRequest.Unmarshal(m, b)
}
func (m *BranchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchRequest.Marshal(b, m, deterministic)
}
func (dst *BranchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchRequest.Merge(dst, src)
}
func (m *BranchRequest) XXX_Size() int {
	return xxx_messageInfo_BranchRequest.Size(m)
}
func (m *BranchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BranchRequest proto.InternalMessageInfo

func (m *BranchRequest) GetRepoId() int64 {
	if m != nil {
		return m.RepoId
	}
	return 0
}

type CommitsRequest struct {
	RepoId               int64    `protobuf:"varint,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	BranchName           string   `protobuf:"bytes,2,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitsRequest) Reset()         { *m = CommitsRequest{} }
func (m *CommitsRequest) String() string { return proto.CompactTextString(m) }
func (*CommitsRequest) ProtoMessage()    {}
func (*CommitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_276dd84b9fe59710, []int{12}
}
func (m *CommitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitsRequest.Unmarshal(m, b)
}
func (m *CommitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitsRequest.Marshal(b, m, deterministic)
}
func (dst *CommitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitsRequest.Merge(dst, src)
}
func (m *CommitsRequest) XXX_Size() int {
	return xxx_messageInfo_CommitsRequest.Size(m)
}
func (m *CommitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitsRequest proto.InternalMessageInfo

func (m *CommitsRequest) GetRepoId() int64 {
	if m != nil {
		return m.RepoId
	}
	return 0
}

func (m *CommitsRequest) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func init() {
	proto.RegisterType((*Project)(nil), "protobuf.Project")
	proto.RegisterType((*Repository)(nil), "protobuf.Repository")
	proto.RegisterType((*Branch)(nil), "protobuf.Branch")
	proto.RegisterType((*Commit)(nil), "protobuf.Commit")
	proto.RegisterType((*Message)(nil), "protobuf.Message")
	proto.RegisterType((*BuildRequest)(nil), "protobuf.BuildRequest")
	proto.RegisterType((*BuildResponse)(nil), "protobuf.BuildResponse")
	proto.RegisterType((*ListProjectsResponse)(nil), "protobuf.ListProjectsResponse")
	proto.RegisterType((*ListBranchesResponse)(nil), "protobuf.ListBranchesResponse")
	proto.RegisterType((*ListCommitsResponse)(nil), "protobuf.ListCommitsResponse")
	proto.RegisterType((*EmptyRequest)(nil), "protobuf.EmptyRequest")
	proto.RegisterType((*BranchRequest)(nil), "protobuf.BranchRequest")
	proto.RegisterType((*CommitsRequest)(nil), "protobuf.CommitsRequest")
	proto.RegisterEnum("protobuf.StatusType", StatusType_name, StatusType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NabuServiceClient is the client API for NabuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NabuServiceClient interface {
	ListProjects(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (NabuService_ListProjectsClient, error)
	ListBranches(ctx context.Context, in *BranchRequest, opts ...grpc.CallOption) (NabuService_ListBranchesClient, error)
	ListCommits(ctx context.Context, in *CommitsRequest, opts ...grpc.CallOption) (NabuService_ListCommitsClient, error)
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (NabuService_BuildClient, error)
}

type nabuServiceClient struct {
	cc *grpc.ClientConn
}

func NewNabuServiceClient(cc *grpc.ClientConn) NabuServiceClient {
	return &nabuServiceClient{cc}
}

func (c *nabuServiceClient) ListProjects(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (NabuService_ListProjectsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NabuService_serviceDesc.Streams[0], "/protobuf.NabuService/ListProjects", opts...)
	if err != nil {
		return nil, err
	}
	x := &nabuServiceListProjectsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NabuService_ListProjectsClient interface {
	Recv() (*ListProjectsResponse, error)
	grpc.ClientStream
}

type nabuServiceListProjectsClient struct {
	grpc.ClientStream
}

func (x *nabuServiceListProjectsClient) Recv() (*ListProjectsResponse, error) {
	m := new(ListProjectsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nabuServiceClient) ListBranches(ctx context.Context, in *BranchRequest, opts ...grpc.CallOption) (NabuService_ListBranchesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NabuService_serviceDesc.Streams[1], "/protobuf.NabuService/ListBranches", opts...)
	if err != nil {
		return nil, err
	}
	x := &nabuServiceListBranchesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NabuService_ListBranchesClient interface {
	Recv() (*ListBranchesResponse, error)
	grpc.ClientStream
}

type nabuServiceListBranchesClient struct {
	grpc.ClientStream
}

func (x *nabuServiceListBranchesClient) Recv() (*ListBranchesResponse, error) {
	m := new(ListBranchesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nabuServiceClient) ListCommits(ctx context.Context, in *CommitsRequest, opts ...grpc.CallOption) (NabuService_ListCommitsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NabuService_serviceDesc.Streams[2], "/protobuf.NabuService/ListCommits", opts...)
	if err != nil {
		return nil, err
	}
	x := &nabuServiceListCommitsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NabuService_ListCommitsClient interface {
	Recv() (*ListCommitsResponse, error)
	grpc.ClientStream
}

type nabuServiceListCommitsClient struct {
	grpc.ClientStream
}

func (x *nabuServiceListCommitsClient) Recv() (*ListCommitsResponse, error) {
	m := new(ListCommitsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nabuServiceClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (NabuService_BuildClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NabuService_serviceDesc.Streams[3], "/protobuf.NabuService/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &nabuServiceBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NabuService_BuildClient interface {
	Recv() (*BuildResponse, error)
	grpc.ClientStream
}

type nabuServiceBuildClient struct {
	grpc.ClientStream
}

func (x *nabuServiceBuildClient) Recv() (*BuildResponse, error) {
	m := new(BuildResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NabuServiceServer is the server API for NabuService service.
type NabuServiceServer interface {
	ListProjects(*EmptyRequest, NabuService_ListProjectsServer) error
	ListBranches(*BranchRequest, NabuService_ListBranchesServer) error
	ListCommits(*CommitsRequest, NabuService_ListCommitsServer) error
	Build(*BuildRequest, NabuService_BuildServer) error
}

func RegisterNabuServiceServer(s *grpc.Server, srv NabuServiceServer) {
	s.RegisterService(&_NabuService_serviceDesc, srv)
}

func _NabuService_ListProjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NabuServiceServer).ListProjects(m, &nabuServiceListProjectsServer{stream})
}

type NabuService_ListProjectsServer interface {
	Send(*ListProjectsResponse) error
	grpc.ServerStream
}

type nabuServiceListProjectsServer struct {
	grpc.ServerStream
}

func (x *nabuServiceListProjectsServer) Send(m *ListProjectsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NabuService_ListBranches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BranchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NabuServiceServer).ListBranches(m, &nabuServiceListBranchesServer{stream})
}

type NabuService_ListBranchesServer interface {
	Send(*ListBranchesResponse) error
	grpc.ServerStream
}

type nabuServiceListBranchesServer struct {
	grpc.ServerStream
}

func (x *nabuServiceListBranchesServer) Send(m *ListBranchesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NabuService_ListCommits_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommitsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NabuServiceServer).ListCommits(m, &nabuServiceListCommitsServer{stream})
}

type NabuService_ListCommitsServer interface {
	Send(*ListCommitsResponse) error
	grpc.ServerStream
}

type nabuServiceListCommitsServer struct {
	grpc.ServerStream
}

func (x *nabuServiceListCommitsServer) Send(m *ListCommitsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NabuService_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NabuServiceServer).Build(m, &nabuServiceBuildServer{stream})
}

type NabuService_BuildServer interface {
	Send(*BuildResponse) error
	grpc.ServerStream
}

type nabuServiceBuildServer struct {
	grpc.ServerStream
}

func (x *nabuServiceBuildServer) Send(m *BuildResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _NabuService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.NabuService",
	HandlerType: (*NabuServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProjects",
			Handler:       _NabuService_ListProjects_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListBranches",
			Handler:       _NabuService_ListBranches_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListCommits",
			Handler:       _NabuService_ListCommits_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Build",
			Handler:       _NabuService_Build_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/nabu.proto",
}

func init() { proto.RegisterFile("protobuf/nabu.proto", fileDescriptor_nabu_276dd84b9fe59710) }

var fileDescriptor_nabu_276dd84b9fe59710 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xc7, 0x3f, 0xdb, 0xad, 0xdd, 0x1c, 0xb7, 0x91, 0xbf, 0x69, 0x45, 0xad, 0x48, 0xbd, 0x68,
	0x56, 0x56, 0xa9, 0xd2, 0x28, 0x6c, 0x10, 0x42, 0x2a, 0x24, 0x44, 0x34, 0x14, 0x9c, 0x6a, 0xd2,
	0xaa, 0xec, 0x2a, 0x27, 0x19, 0x52, 0x43, 0x1c, 0x1b, 0xcf, 0x18, 0x29, 0xcf, 0xc2, 0x0b, 0xf0,
	0x98, 0xc8, 0x9e, 0xf1, 0x25, 0x71, 0x85, 0x60, 0xe7, 0x73, 0xf1, 0xef, 0x5c, 0xfe, 0x67, 0x60,
	0x3f, 0x8a, 0x43, 0x1e, 0x4e, 0x92, 0x2f, 0x17, 0x4b, 0x6f, 0x92, 0xb4, 0x33, 0x0b, 0xed, 0xe4,
	0xce, 0xd6, 0xc9, 0x3c, 0x0c, 0xe7, 0x0b, 0x7a, 0x51, 0x64, 0x71, 0x3f, 0xa0, 0x8c, 0x7b, 0x41,
	0x24, 0x52, 0xf1, 0x08, 0x8c, 0x9b, 0x38, 0xfc, 0x4a, 0xa7, 0x1c, 0x35, 0x41, 0xf5, 0x67, 0xb6,
	0x72, 0xaa, 0x38, 0x1a, 0x51, 0xfd, 0x19, 0x3a, 0x80, 0x6d, 0xee, 0xf3, 0x05, 0xb5, 0xd5, 0x53,
	0xc5, 0x69, 0x10, 0x61, 0xa0, 0x63, 0x80, 0x98, 0x46, 0x21, 0xf3, 0x79, 0x18, 0xaf, 0x6c, 0x2d,
	0x0b, 0x55, 0x3c, 0x38, 0x02, 0x20, 0x85, 0x55, 0x63, 0x22, 0xd8, 0x5a, 0x7a, 0x41, 0x8e, 0xcc,
	0xbe, 0x91, 0x05, 0xda, 0x37, 0x9a, 0xa3, 0xd2, 0x4f, 0x74, 0x0e, 0x3b, 0x93, 0xd8, 0x5b, 0x4e,
	0x1f, 0x29, 0xb3, 0xb7, 0x4e, 0x35, 0xc7, 0xec, 0x5a, 0xed, 0x7c, 0x82, 0x76, 0x2f, 0x8b, 0x90,
	0x22, 0x03, 0x7f, 0x06, 0x5d, 0xf8, 0xfe, 0xaa, 0xda, 0x19, 0x18, 0xd3, 0x30, 0x08, 0x7c, 0xce,
	0x6c, 0x6d, 0x13, 0xdd, 0xcf, 0x02, 0x24, 0x4f, 0xc0, 0x4b, 0xd0, 0x85, 0x0b, 0xd9, 0x60, 0x04,
	0x94, 0x31, 0x6f, 0x4e, 0x33, 0x7c, 0x83, 0xe4, 0x66, 0xda, 0x3d, 0x7b, 0xf4, 0x64, 0x89, 0xf4,
	0x13, 0xbd, 0x84, 0x46, 0xb1, 0xe5, 0x6c, 0x2a, 0xb3, 0xdb, 0x6a, 0x0b, 0x1d, 0xca, 0x52, 0xb7,
	0x79, 0x06, 0x29, 0x93, 0xf1, 0x4f, 0x05, 0x8c, 0x4f, 0x92, 0xbb, 0x39, 0xcb, 0x1a, 0x55, 0xfd,
	0x07, 0x6a, 0xb5, 0x77, 0x6d, 0xbd, 0xf7, 0x73, 0xd0, 0x19, 0xf7, 0x78, 0x92, 0x6e, 0x59, 0x71,
	0x9a, 0xdd, 0x83, 0x92, 0x34, 0xce, 0xfc, 0xb7, 0xab, 0x88, 0x12, 0x99, 0x83, 0x2f, 0x61, 0xb7,
	0x97, 0xf8, 0x8b, 0x19, 0xa1, 0xdf, 0x13, 0xca, 0x38, 0x3a, 0x02, 0x88, 0xc4, 0xe9, 0x3c, 0x14,
	0x9d, 0x36, 0xa4, 0x67, 0x38, 0xab, 0x2f, 0x06, 0xbf, 0x86, 0x3d, 0x09, 0x60, 0x51, 0xb8, 0x64,
	0x14, 0x3d, 0x5f, 0xdf, 0xaa, 0xd9, 0xfd, 0xbf, 0x6c, 0x40, 0xee, 0xa1, 0x68, 0x16, 0xf7, 0xe1,
	0xe0, 0xa3, 0xcf, 0xb8, 0xbc, 0x56, 0x56, 0x85, 0xc8, 0xa2, 0x75, 0x88, 0x4c, 0x26, 0x79, 0x06,
	0x7e, 0x23, 0x20, 0x3d, 0x79, 0x3b, 0x05, 0xc4, 0x01, 0x5d, 0xdc, 0x93, 0x64, 0xd4, 0xef, 0x4d,
	0xc6, 0xf1, 0x25, 0xec, 0xa7, 0x04, 0x71, 0x17, 0x6b, 0x00, 0x71, 0x35, 0x75, 0x80, 0xbc, 0x2a,
	0x19, 0xc7, 0x4d, 0xd8, 0x1d, 0x04, 0x11, 0x5f, 0xc9, 0x35, 0x62, 0x07, 0xf6, 0x64, 0x09, 0xb9,
	0xd7, 0x43, 0x30, 0xd2, 0xf7, 0x54, 0x2e, 0x55, 0x4f, 0xcd, 0xe1, 0x0c, 0x7f, 0x80, 0x66, 0x51,
	0xf6, 0xcf, 0xa9, 0xe8, 0x04, 0x4c, 0xd1, 0xef, 0x43, 0xe5, 0x01, 0x80, 0x70, 0xb9, 0x5e, 0x40,
	0xcf, 0xae, 0x01, 0x4a, 0x89, 0x91, 0x09, 0xc6, 0x9d, 0x7b, 0xed, 0x8e, 0xee, 0x5d, 0xeb, 0xbf,
	0xd4, 0x18, 0xdf, 0xf5, 0xfb, 0x83, 0xf1, 0xd8, 0x52, 0x50, 0x03, 0xb6, 0x07, 0x84, 0x8c, 0x88,
	0xa5, 0xa6, 0xfe, 0xfb, 0xb7, 0xc4, 0x1d, 0xba, 0xef, 0x2d, 0x2d, 0x35, 0x6e, 0x06, 0xee, 0xbb,
	0xd4, 0xd8, 0xea, 0xfe, 0x52, 0xc1, 0x74, 0xbd, 0x49, 0x32, 0xa6, 0xf1, 0x0f, 0x7f, 0x4a, 0xd1,
	0x15, 0xec, 0x56, 0xa5, 0x42, 0xcf, 0xca, 0x65, 0x54, 0x47, 0x6f, 0x1d, 0x97, 0xfe, 0xa7, 0xa4,
	0xed, 0x28, 0x68, 0x28, 0x48, 0xb9, 0x5e, 0xe8, 0xb0, 0xa6, 0xcb, 0xd3, 0xa8, 0x4d, 0x81, 0x3b,
	0x0a, 0xba, 0x02, 0xb3, 0x22, 0x1c, 0xb2, 0x37, 0x05, 0xca, 0x97, 0xda, 0x3a, 0x5a, 0x47, 0x6d,
	0x28, 0xdd, 0x51, 0xd0, 0x2b, 0xd8, 0xce, 0xee, 0xb8, 0x3a, 0x57, 0xf5, 0x65, 0xb4, 0x0e, 0x6b,
	0xfe, 0xfc, 0xdf, 0x89, 0x9e, 0x45, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xed, 0x29,
	0xc5, 0xb8, 0x05, 0x00, 0x00,
}
