// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/nabu.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Story struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score                int32    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	By                   string   `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	Time                 int32    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Url                  string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Story) Reset()         { *m = Story{} }
func (m *Story) String() string { return proto.CompactTextString(m) }
func (*Story) ProtoMessage()    {}
func (*Story) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_82a4baa8cb79ac63, []int{0}
}
func (m *Story) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Story.Unmarshal(m, b)
}
func (m *Story) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Story.Marshal(b, m, deterministic)
}
func (dst *Story) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Story.Merge(dst, src)
}
func (m *Story) XXX_Size() int {
	return xxx_messageInfo_Story.Size(m)
}
func (m *Story) XXX_DiscardUnknown() {
	xxx_messageInfo_Story.DiscardUnknown(m)
}

var xxx_messageInfo_Story proto.InternalMessageInfo

func (m *Story) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Story) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Story) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Story) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

func (m *Story) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Story) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ListStoriesResponse struct {
	Story                *Story   `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStoriesResponse) Reset()         { *m = ListStoriesResponse{} }
func (m *ListStoriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListStoriesResponse) ProtoMessage()    {}
func (*ListStoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_82a4baa8cb79ac63, []int{1}
}
func (m *ListStoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStoriesResponse.Unmarshal(m, b)
}
func (m *ListStoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStoriesResponse.Marshal(b, m, deterministic)
}
func (dst *ListStoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStoriesResponse.Merge(dst, src)
}
func (m *ListStoriesResponse) XXX_Size() int {
	return xxx_messageInfo_ListStoriesResponse.Size(m)
}
func (m *ListStoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStoriesResponse proto.InternalMessageInfo

func (m *ListStoriesResponse) GetStory() *Story {
	if m != nil {
		return m.Story
	}
	return nil
}

type ListStoriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStoriesRequest) Reset()         { *m = ListStoriesRequest{} }
func (m *ListStoriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListStoriesRequest) ProtoMessage()    {}
func (*ListStoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nabu_82a4baa8cb79ac63, []int{2}
}
func (m *ListStoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStoriesRequest.Unmarshal(m, b)
}
func (m *ListStoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStoriesRequest.Marshal(b, m, deterministic)
}
func (dst *ListStoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStoriesRequest.Merge(dst, src)
}
func (m *ListStoriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListStoriesRequest.Size(m)
}
func (m *ListStoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStoriesRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Story)(nil), "proto.Story")
	proto.RegisterType((*ListStoriesResponse)(nil), "proto.ListStoriesResponse")
	proto.RegisterType((*ListStoriesRequest)(nil), "proto.ListStoriesRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HackerNewsServiceClient is the client API for HackerNewsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HackerNewsServiceClient interface {
	ListStories(ctx context.Context, in *ListStoriesRequest, opts ...grpc.CallOption) (HackerNewsService_ListStoriesClient, error)
}

type hackerNewsServiceClient struct {
	cc *grpc.ClientConn
}

func NewHackerNewsServiceClient(cc *grpc.ClientConn) HackerNewsServiceClient {
	return &hackerNewsServiceClient{cc}
}

func (c *hackerNewsServiceClient) ListStories(ctx context.Context, in *ListStoriesRequest, opts ...grpc.CallOption) (HackerNewsService_ListStoriesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HackerNewsService_serviceDesc.Streams[0], "/proto.HackerNewsService/ListStories", opts...)
	if err != nil {
		return nil, err
	}
	x := &hackerNewsServiceListStoriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HackerNewsService_ListStoriesClient interface {
	Recv() (*ListStoriesResponse, error)
	grpc.ClientStream
}

type hackerNewsServiceListStoriesClient struct {
	grpc.ClientStream
}

func (x *hackerNewsServiceListStoriesClient) Recv() (*ListStoriesResponse, error) {
	m := new(ListStoriesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HackerNewsServiceServer is the server API for HackerNewsService service.
type HackerNewsServiceServer interface {
	ListStories(*ListStoriesRequest, HackerNewsService_ListStoriesServer) error
}

func RegisterHackerNewsServiceServer(s *grpc.Server, srv HackerNewsServiceServer) {
	s.RegisterService(&_HackerNewsService_serviceDesc, srv)
}

func _HackerNewsService_ListStories_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListStoriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HackerNewsServiceServer).ListStories(m, &hackerNewsServiceListStoriesServer{stream})
}

type HackerNewsService_ListStoriesServer interface {
	Send(*ListStoriesResponse) error
	grpc.ServerStream
}

type hackerNewsServiceListStoriesServer struct {
	grpc.ServerStream
}

func (x *hackerNewsServiceListStoriesServer) Send(m *ListStoriesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _HackerNewsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HackerNewsService",
	HandlerType: (*HackerNewsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListStories",
			Handler:       _HackerNewsService_ListStories_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/nabu.proto",
}

func init() { proto.RegisterFile("proto/nabu.proto", fileDescriptor_nabu_82a4baa8cb79ac63) }

var fileDescriptor_nabu_82a4baa8cb79ac63 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x31, 0x4f, 0x43, 0x31,
	0x0c, 0x84, 0xf5, 0xd2, 0xa6, 0x12, 0x2e, 0x42, 0xc5, 0x74, 0x08, 0x9d, 0xaa, 0x4c, 0x9d, 0x0a,
	0x2a, 0x13, 0x7f, 0x00, 0x31, 0x20, 0x86, 0x74, 0x64, 0x6a, 0x5e, 0x3d, 0x44, 0x94, 0xa6, 0xc4,
	0x79, 0xa0, 0xfc, 0x7b, 0x14, 0x87, 0x01, 0x04, 0x53, 0xce, 0x77, 0xbe, 0xf8, 0x83, 0xd9, 0x29,
	0xc5, 0x1c, 0x6f, 0x8e, 0x3b, 0x3f, 0xac, 0x45, 0xa2, 0x96, 0xc7, 0x16, 0xd0, 0xdb, 0x1c, 0x53,
	0xc1, 0x0b, 0x50, 0x61, 0x6f, 0xba, 0x65, 0xb7, 0xd2, 0x4e, 0x85, 0x3d, 0xce, 0x41, 0x73, 0x1f,
	0x13, 0x19, 0x25, 0x56, 0x1b, 0xaa, 0x9b, 0x43, 0x3e, 0x90, 0x19, 0x2d, 0xbb, 0xd5, 0x99, 0x6b,
	0x43, 0xed, 0xfa, 0x62, 0xc6, 0x62, 0x29, 0x5f, 0x10, 0x61, 0x9c, 0xc3, 0x1b, 0x19, 0x2d, 0x55,
	0xd1, 0x38, 0x83, 0xd1, 0x90, 0x0e, 0x66, 0x22, 0x4b, 0x55, 0xda, 0x7b, 0xb8, 0x7a, 0x0a, 0x9c,
	0xeb, 0xf9, 0x40, 0xec, 0x88, 0x4f, 0xf1, 0xc8, 0x84, 0x16, 0x34, 0x57, 0x22, 0x61, 0x99, 0x6e,
	0xce, 0x1b, 0xef, 0x5a, 0x28, 0x5d, 0x8b, 0xec, 0x1c, 0xf0, 0x57, 0xf5, 0x7d, 0x20, 0xce, 0x9b,
	0x17, 0xb8, 0x7c, 0xdc, 0xf5, 0xaf, 0x94, 0x9e, 0xe9, 0x93, 0xb7, 0x94, 0x3e, 0x42, 0x4f, 0xf8,
	0x00, 0xd3, 0x1f, 0xab, 0x78, 0xfd, 0xfd, 0xdd, 0xdf, 0xfa, 0x62, 0xf1, 0x5f, 0xd4, 0xa0, 0x6e,
	0x3b, 0x3f, 0x91, 0xf0, 0xee, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xde, 0x0e, 0x66, 0x4e, 0x4a, 0x01,
	0x00, 0x00,
}
