debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
      [entryPoints.https.redirect]
      regex = "^https://www.svoerazvitie.com/(.*)"
      replacement = "https://svoerazvitie.com/$1"
      permanent = true
  [entryPoints.https.tls]

[file]
  filename = "/etc/traefik-rules.toml"
  watch = true

[acme]
email = "afanasy.barbarov@hotmail.com"
storage = "/apps/acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging = true

  [acme.httpChallenge]
    entryPoint = "http"

#  [acme.dnsChallenge]
#    provider = "namecheap"
#    delayBeforeCheck = 0

  [[acme.domains]]
    main = "nabu.app"
    sans = ["nabu.app", "live.nabu.app", "tg.nabu.app"]

  [[acme.domains]]
    main = "barbarov.com"

  [[acme.domains]]
    main = "test.firstfile.ru"

  [[acme.domains]]
    main = "svoerazvitie.com"
    sans = ["svoerazvitie.com", "www.svoerazvitie.com"]