[backends]

  [backends.backend-nabu]
    [backends.backend-nabu.servers]
      [backends.backend-nabu.servers.server-blue]
        url = "http://127.0.0.1:10001"
        weight = 1
      [backends.backend-nabu.servers.server-green]
        url = "http://127.0.0.1:10002"
        weight = 2
    [backends.backend-nabu.maxconn]
       amount = 10
       extractorfunc = "client.ip"
    [backends.backend-nabu.loadbalancer.stickiness]

  [backends.backend-barbarov]
    [backends.backend-barbarov.servers]
      [backends.backend-barbarov.servers.server-blue]
        url = "http://127.0.0.1:10101"
        weight = 1
      [backends.backend-barbarov.servers.server-green]
        url = "http://127.0.0.1:10102"
        weight = 2
    [backends.backend-barbarov.maxconn]
       amount = 10
       extractorfunc = "client.ip"
    [backends.backend-barbarov.loadbalancer.stickiness]

[frontends]

  [frontends.frontend-nabu]
    backend = "backend-nabu"
    passHostHeader = true
    [frontends.frontend-nabu.routes]
      [frontends.frontend-nabu.routes.route0]
        rule = "Host:nabu.app"

  [frontends.frontend-barbarov]
    backend = "backend-barbarov"
    passHostHeader = true
    [frontends.frontend-barbarov.routes]
      [frontends.frontend-barbarov.routes.route0]
        rule = "Host:barbarov.app"
