debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[file]
  filename = "./rules.toml"
  watch = true

[acme]
email = "afanasy.barbarov@hotmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
acmeLogging=true

  [acme.httpChallenge]
    entryPoint = "http"

#  [acme.dnsChallenge]
#    provider = "namecheap"
#    delayBeforeCheck = 0

  [[acme.domains]]
    main = "nabu.app"
    sans = ["nabu.app", "live.nabu.app"]

  [[acme.domains]]
    main = "barbarov.com"